services:
  backend:
    build:
      target: dev
    volumes:
      - ./backend:/app
      - /var/log/alter-ego:/var/log/alter-ego
    command: air -c air.toml

  line-backend:
    build:
      target: dev
    volumes:
      - ./line/backend:/app
    command: yarn run start:dev

  llm:
    build:
      target: dev
    volumes:
      - ./llm:/app
    ports:
      - "50052:50052"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: uv run watchdog_runner.py
