version: '3.8'

services:
  backend:
    build:
      target: dev
    command: air -c air.toml

  line-backend:
    build:
      target: dev
    volumes:
      - ./line/backend:/app
    command: yarn run start:dev

  llm:
    build:
      target: dev
    volumes:
      - ./llm:/app
    command: pnpm run dev
