events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # 未設定のドメインに対するリクエストを拒否
    server {
        listen 80 default_server;
        listen 443 ssl default_server;

        ssl_certificate     /etc/letsencrypt/live/alter-ego.fuu.jp/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/alter-ego.fuu.jp/privkey.pem;

        server_name _;

        return 444;
    }

    server {
        listen 443 ssl;

        ssl_certificate     /etc/letsencrypt/live/alter-ego.fuu.jp/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/alter-ego.fuu.jp/privkey.pem;

        server_name alter-ego.fuu.jp;

        root /usr/share/nginx/html;
        index index.html;

        access_log /var/log/nginx/alter-ego.access.log;
        error_log /var/log/nginx/alter-ego.error.log;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    server {
        listen 443 ssl;

        ssl_certificate     /etc/letsencrypt/live/alter-ego.fuu.jp/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/alter-ego.fuu.jp/privkey.pem;

        server_name api.line.alter-ego.fuu.jp;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location / {
            proxy_pass http://host.docker.internal:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 443 ssl;

        ssl_certificate     /etc/letsencrypt/live/alter-ego.fuu.jp/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/alter-ego.fuu.jp/privkey.pem;

        server_name dify.alter-ego.fuu.jp;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location / {
            proxy_pass http://host.docker.internal:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 443 ssl;

        ssl_certificate     /etc/letsencrypt/live/alter-ego.fuu.jp/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/alter-ego.fuu.jp/privkey.pem;

        server_name api.backend.alter-ego.fuu.jp;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location / {
            proxy_pass http://host.docker.internal:50080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # certbot 用サーバー設定
    server {
        listen 80;

        server_name
            alter-ego.fuu.jp
            dify.alter-ego.fuu.jp
            api.line.alter-ego.fuu.jp;
            api.backend.alter-ego.fuu.jp;

        location /.well-known/acme-challenge/ {
            root /usr/share/nginx/html;
            allow all;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }
}
