syntax = "proto3";

package backend.v1;

option go_package = "github.com/alpha-bbb/alter-ego/backend/gen/grpc/backend/v1";

service BackendService {
  rpc Talk(TalkRequest) returns (TalkResponse) {}
  rpc Subscribe(SubscribeRequest) returns (SubscribeResponse) {}
}

message TalkRequest {
  enum ActionKind {
    ACTION_KIND_UNSPECIFIED = 0; // 未定義
    ACTION_KIND_END_CONVERSATION = 1; // 会話を終わらせる
  }
  repeated TalkHistory histories = 1; // 発言履歴
  ActionKind action_kind = 2; // アクションの種類
  Account account = 3; // アカウント情報
}

message TalkHistory {
  string date = 1; // ISO 8601 date format (2021-05-22T00:00:00Z)
  User user = 2; // 発言したユーザー
  string message = 3; // 発言内容
}

message User {
  enum UserRole {
    UNSPECIFIED = 0; // 未定義
    SELF = 1; // 私
    YOU = 2;  // あなた
  }
  string user_id = 1; // ユーザーを一意に識別するID
  string name = 2; // ユーザー名
  UserRole role = 3; // ユーザーの役割
}

// 会話のレスポンス
// 通常は候補のメッセージを返す
// 利用制限などでエラーが発生した場合はエラーメッセージを返す
// エラーメッセージはmessageのindex=0に設定する
message TalkResponse {
  enum TalkResponseStatus {
    TALK_RESPONSE_STATUS_UNSPECIFIED = 0; // 未定義
    TALK_RESPONSE_STATUS_SUCCESS = 1; // 成功
    TALK_RESPONSE_STATUS_ERROR = 2; // エラー
    TALK_RESPONSE_STATUS_LIMIT = 3; // 回数利用制限
  }
  repeated string message = 1; // 候補のメッセージ
  TalkResponseStatus status = 2; // ステータス
}

// アカウント情報
message Account {
  enum PlatformType {
    PLATFORM_UNSPECIFIED = 0; // 未定義
    PLATFORM_LINE = 1; // LINE
  }
  PlatformType platform_type = 1; // プラットフォームの種類
  string account_id = 2; // アカウントを一意に識別するID
}

// サブスクを行うためのリクエスト
message SubscribeRequest {
  enum SubscribeAction {
    SUBSCRIBE_ACTION_UNSPECIFIED = 0; // 未定義
    SUBSCRIBE_ACTION_START = 1; // サブスク開始
    SUBSCRIBE_ACTION_CANCEL = 2; // サブスクキャンセル
    SUBSCRIBE_ACTION_CHECK = 3; // サブスクチェック
  }
  Account account = 1;
  SubscribeAction action = 2;
}

// サブスクを行うためのレスポンス
// 何かしらのサイトにリダイレクトする場合は、redirect_urlにURLを設定する
// 例: サブスクするためにStripeのページにリダイレクトする場合
message SubscribeResponse {
  enum SubscribeStatus {
    SUBSCRIBE_UNSPECIFIED = 0;       // 未定義
    SUBSCRIBE_NOT_SUBSCRIBED = 1;      // サブスクしていない状態
    SUBSCRIBE_PROCESSING = 2;          // サブスク処理中
    SUBSCRIBE_ACTIVE = 3;              // サブスク中
  }
  SubscribeStatus status = 1; // ステータス
  string message = 2; // メッセージ
  string redirect_url = 3; // リダイレクトURL
  int64 expire_at = 4; // サブスクの有効期限 (Unix Time)
}
